### ISSUE TITLE
Saved preferences do not apply after restarting phone

### ISSUE THREAD

**Issue by IveMalfunctioned** [florisboard/florisboard#1726]
#### Short description
Describe the bug in a short but concise way.
After florisboard starts during boot my saved preferences did not apply until restarting florisboard manually

#### Steps to reproduce
1. Restart phone
2. Settings do not apply
3. Manually restarting florisboard fixes this

#### Environment information
- FlorisBoard Version: 0.3.13
- Install Source: F-Droid
- Device: OnePlus Nord N200
- Android: "Oxygen OS" Android 11.0.6.0.DE17AA

**Comment by z0xrv** [comment]
I can confirm this happens to me, the themes I loaded still there

**Comment by patrickgold** [comment]
Thanks for your bug report!

How does the latest stable release, 0.3.14 behave in this instance?

**Comment by z0xrv** [comment]
I'm using 0.3.15-beta01

**Comment by IveMalfunctioned** [comment]
@patrickgold I can't install the 0.3.14 apk, it just says "App not installed." also tried force stopping florisboard to update, but that didn't work

**Comment by IveMalfunctioned** [comment]
Nope

**Comment by Takokeshi** [comment]
F-Droid releases and github releases are built by different people and signed with different keys. If you installed from F-Droid, you must update from F-Droid.

**Comment by notjedi** [comment]
can second this, it happens even on my phone.

**additional info**
* version: `0.3.15`.
* OS: `LineageOS 18.1`.
* device: `miatoll - Poco M2 Pro`.

willing to provide more info. and/or help closing this issue.

**Comment by patrickgold** [comment]
I still do not know exactly what is causing this issue and it really bugs me, because I understand that it is a really annoying bug.

> EDIT: seems like this doesn't happen with many people, so we all must have something in common ig?

Either only a few people notice and report it or it just happens to a few people. The only common trend I found is that all these reports came from Android 11 devices (custom and stock ROMs mixed). Maybe I need to look into the changelog of A11 to see if something has changed in the bootup context that I missed. But interestingly on my OnePlus with A11 this bug does not occur at all, so not sure about my theory either.

**Comment by BrudiBanani** [comment]
I also experience this issue on Android 12 on Asus Zenfone 8 with Stock ROM.
After a restart florisboard will load default values for typing in password and than it will not apply my custom config until a manual restart.

**Comment by notjedi** [comment]
i did some findings and here is what i found. this issue happens only when:
1. force restarting the phone(holding the power button long enough)
2. powering off the phone (but i suspect that this is only happening on my phone cause LineageOS has some problems with powering off, it actually force restarts my phone when powering off.

Note: this does not happen when during normal restarts(atleast for me).

**Comment by theotheroracle** [comment]
it happens consistently every time for me, not just when i force restart, or power-off

**Comment by tsiflimagas** [comment]
I can reproduce it by killing the app 2-3 times, but only on debug builds, somehow. On release builds, it happens every now and then after rebooting, but the frequency seems random. I'm on Android 12.1.

**Comment by patrickgold** [comment]
Above PR should be a fix for this bug, at least I wasn't able to reproduce it anymore after applying the fix. If possible, could some of you test out the debug build and give feedback if this is now fixed? (debug build installs separately and does not touch the main installation). This would be incredible help!

Either way this fix (or adjusted based on feedback if needed) will be included in the next beta release and then hopefully there isn't another way how the preferences can accidentally be overwritten again.

**Comment by tsiflimagas** [comment]
I tried again and again (more than 50 times in sum, probably) and couldn't reproduce it either. Tried several times on a beta build too and went fine as well, also rebooted a few times and settings still persisted as expected. For the record, my storage isn't encrypted (I know, bad decision, not recommended). Not sure if it could make a difference in this case. For me, it seems fixed, since I'm totally sure it would have occurred again after that many iterations. Great work!

**Comment by notjedi** [comment]
@patrickgold where do i get the debug build? do i need to build it w android studio?

**Comment by tsiflimagas** [comment]
The artifact can he found here https://github.com/florisboard/florisboard/actions/runs/2373952609. Debug builds are built automatically by GitHub Actions when pushing in pull requests.

**Comment by notjedi** [comment]
still facing the issue, this does not fix the issue even in the debug build

**Comment by notjedi** [comment]
but one thing that might possibly be insightful is that, after rebooting the phone, only the preferences of florisboard debug build was reset and the normal release build was working fine. i am just randomly guessing here but it feels like maybe the service is being force shutdown and it's not able to save the prefs to the disk? but it doesn't make sense because the prefs are saved as soon as you commit the changes

**Comment by patrickgold** [comment]
> but one thing that might possibly be insightful is that, after rebooting the phone, only the preferences of florisboard debug build was reset and the normal release build was working fine.

When the device restarts, only the last default keyboard will be loaded and run again, so if it was FlorisBoard Debug (which is the test case here) then it makes sense that only the Debug version is affected. So if you try rebooting the device with FlorisBoard debug, does only the preferences get reset or also custom themes, and does killing and starting the Debug version again after login reload the prefs or are they gone entirely?

**Comment by patrickgold** [comment]
> I tried again and again (more than 50 times in sum, probably) and couldn't reproduce it either. Tried several times on a beta build too and went fine as well, also rebooted a few times and settings still persisted as expected.

I think maybe my fix just made the bug even rarer but not entirely fix it, atm I am very unsure. The problem is that my method to reproduce this bug (writing a preference before loading the preferences, which happens in the logic too just a bit later normally) absolutely does not want to work anymore after the fix, so I assumed this behavior is now fixed after a lot of restarts and force closes.

> For the record, my storage isn't encrypted (I know, bad decision, not recommended)

Modern Android version allows the storage to not be encrypted? That's new for me, I assumed the credential-based file encryption is standard by now.

**Comment by notjedi** [comment]
> When the device restarts, only the last default keyboard will be loaded and run again, so if it was FlorisBoard Debug (which is the test case here) then it makes sense that only the Debug version is affected. So if you try rebooting the device with FlorisBoard debug, does only the preferences get reset or also custom themes, and does killing and starting the Debug version again after login reload the prefs or are they gone entirely?

killing the app doesn't reset the prefs. after rebooting all the prefs are reset, including the themes (it's basically like a newly installed app). killing the app after rebooting doesn't seem to fix the issue. so basically everytime i reboot, it's like the app has cleared it's data.

**Comment by patrickgold** [comment]
> killing the app doesn't reset the prefs.

That's at least partly good news, this also caused rare issues sometimes.

> after rebooting all the prefs are reset, including the themes (it's basically like a newly installed app). killing the app after rebooting doesn't seem to fix the issue. so basically everytime i reboot, it's like the app has cleared it's data.

During the first login after reboot this is expected, because the user data is not yet encrypted. The interesting part is after successful initial login, which themes/prefs are loaded in any text field you tap in?

**Comment by notjedi** [comment]
> During the first login after reboot this is expected, because the user data is not yet encrypted.

did you mean "not yet decrypted"?
> The interesting part is after successful initial login, which themes/prefs are loaded in any text field you tap in?

the default out of the box one, floris night (with border).

**Comment by theotheroracle** [comment]
i couldn't reproduce the bug in the beta build

**Comment by notjedi** [comment]
the debug build fixes it for you? weird. btw, do you see the onboarding screen after rebooting in the release build?

**Comment by GoRaN909** [comment]
I never had this bug nor in Stable or Beta versions :/

**Comment by notjedi** [comment]
@GoRaN909 yeah, it's pretty rare and many are not able to reproduce this locally. so we can't find the cause of this issue or even anything common b/w the people who have this issue.

**Comment by GoRaN909** [comment]
@notjedi I think that bug is mostly happens on AOSP based ROMs like Android ONE and OnePlus devices.

**Comment by theotheroracle** [comment]
unsure if its relevant at all but i do have microg

**Comment by tsiflimagas** [comment]
> Modern Android version allows the storage to not be encrypted?

Well, I'm not totally sure, as it could also be some patch custom roms use, but yeah, if you remove encryption entries from the fstab and format the data partition, you'll boot decrypted. If you join some relevant telegram groups, you'll surely bump into flashable zip files which do this job (some also edit boot image). When such tools move around too much though, the negative effect is that many people use them being unaware of the possible consequences.

**Comment by GoRaN909** [comment]
> That's definitely possible because this bug was not really occurring for many users to begin with, there has to be something in common which causes this bug on the few selected devices. The only common factor I found is that the Android level is 11 or 12, but even that doe snot mean much as my A11/12 devices run fine, even the stock emulators without Google APIs.

That's so strange I don't know what to do, Ahh you remembered me after A12 improvements for sound & vibration features the Vibrator is working very good even when dark mode and power saving option is Enabled but the Sounds doesn't work at all I tried with turning off the dark mode and power saving mode but still the sounds not work when you typing or tap any other buttons please take a look at them and I wish you do fix that just like the Vibration is there :)

**Comment by notjedi** [comment]
even i have microg, with lineageos. not sure how it's related but yeah.

**Comment by notjedi** [comment]
had a new ota update for lineage os today and it magically fixed the issue after updating

**Comment by patrickgold** [comment]
> had a new ota update for lineage os today and it magically fixed the issue after updating

Could be an indication that there's a bug at the OS level with the device-protected/credential storage switch. Would be an explanation why most users don't experience this bug.

**Comment by billie80** [comment]
For me this also happens, but the settings are only gone after updates to florisboard. It does not happen with every update though. Last time for the latest 0.13.16 beta04. I think it did not happen for the previous betas of 0.13.16. This is on Android 10 btw.

**Comment by theotheroracle** [comment]
for what its worth i havent noticed this issue anymore

**Comment by tsiflimagas** [comment]
Yeah, me neither. Right after that initial fix, I actually (like others) got the bug again, one or two times after rebooting, but it's been months since then, and I never got it again. Maybe it got fixed by accident from an unrelated change? I'm curious to hear if anyone else experienced it recently.

**Comment by billie80** [comment]
Didn't experience it either withthe latest releases!

**Comment by patrickgold** [comment]
I haven't changed anything explicitly in this regard since my latest fix attempt, so if it is fixed it is completely by accident. This isn't good however, because if this bug can be fixed by accident it can be introduced by accident again.

**Comment by theotheroracle** [comment]
i coukd try to narrow down what commit it was fixed in with the ci builds, will take some time tho lol

**Comment by tsiflimagas** [comment]
Could it be something in this commit https://github.com/patrickgold/jetpref/commit/2301d0ede7053841b5e8231522ef85f640d8e127 ? I don't understand the code, it's just near the place the fix commit touched.

**Comment by patrickgold** [comment]
> Could it be something in this commit https://github.com/patrickgold/jetpref/commit/2301d0ede7053841b5e8231522ef85f640d8e127 ?

That specific code shouldn't affect this issue, as it just changes the representation of enum values in the serialized state, whereas this issue affects all types of preference data. Either a change in this repo somehow fixed the issue or a change in a dependency, but like I said I don't know which.

**Comment by theotheroracle** [comment]
after not experiencing this issue it's suddenly come up again, it's entirely possible it has something to do with the fact i'm now using a google pixel 1 with android 11, whereas i was previously using 12 ? but what i suspect is mostly likely to be the cause is that this phone has a shoddy battery that will sometimes crash, ( not shutdown, just straight to blackscreen ) so that may be part of the issue, the app might get a shutdown signal and try to save preferences and then corrupt them ? dunno, maybe some system where the original settings aren't touched, but they're written to a secondary file which is applied at next start of the keyboard, and if it's corrupted, fallback to the previous file would address the issue ? i know you're busy with nlp stuff rn tho and this would prolly be a pretty big change, but i thought i'd maybe give my 2 cents on what the possible cause / fix could be, thx for the good work as always, cheers

**Comment by Alamingazipur** [comment]
> 
> 
> #### Short description
> Describe the bug in a short but concise way.
> After florisboard starts at boot my saved preferences did not apply until restarting florisboard manually
> 
> #### Steps to reproduce
> 1. Restart phone
> 2. Settings do not apply
> 3. Manually restarting florisboard fixes this
> 
> #### Environment information
> - FlorisBoard Version: 0.3.13
> - Install Source: F-Droid
> - Device: OnePlus Nord N200
> - Android: "Oxygen OS" Android 11.0.6.0.DE17AA
>

**Comment by Alamingazipur** [comment]
> 
> 
> #### Short description
> Describe the bug in a short but concise way.
> After florisboard starts at boot my saved preferences did not apply until restarting florisboard manually
> 
> #### Steps to reproduce
> 1. Restart phone
> 2. Settings do not apply
> 3. Manually restarting florisboard fixes this
> 
> #### Environment information
> - FlorisBoard Version: 0.3.13
> - Install Source: F-Droid
> - Device: OnePlus Nord N200
> - Android: "Oxygen OS" Android 11.0.6.0.DE17AA
>

**Comment by Alamingazipur** [comment]
> > but one thing that might possibly be insightful is that, after rebooting the phone, only the preferences of florisboard debug build was reset and the normal release build was working fine.
> 
> When the device restarts, only the last default keyboard will be loaded and run again, so if it was FlorisBoard Debug (which is the test case here) then it makes sense that only the Debug version is affected. So if you try rebooting the device with FlorisBoard debug, does only the preferences get reset or also custom themes, and does killing and starting the Debug version again after login reload the prefs or are they gone entirely?

**Comment by sleepysleepyhead** [comment]
just saying that i had zero issues with florisboard before but then i changed the main language from american english to bri'ish and now i have this problem...

**Comment by sleepysleepyhead** [comment]
an update: i switched back to american english and the settings stopped going back to default. even with forced reboots

**Comment by tsiflimagas** [comment]
Thank you @sleepysleepyhead for the observation! Also, @axelsimon faced this bug and he happened to be using English (United Kingdom) layout too. That's suspicious...

**Comment by theotheroracle** [comment]
i think i may have been on the canadian layout when i was experiencing this tbh

**Comment by atikattar1104** [comment]
> For me this also happens, but the settings are only gone after updates to florisboard. It does not happen with every update though. 

> This is on Android 10 btw. If more information is required I will gladly provide it if possible.

I Agree With This. Only Happens Sometimes (1-2 Times, In 2-3 Years To Be Exact), But Entire App Resets To Default As Initial Install.

**Comment by rancidfrog** [comment]
The problem occurs with me when phone switches off due to low battery.
After connecting phone to charge and switch on, florisboard loses all settings,

**Comment by freema11oc** [comment]
just happened to me.

**Comment by lm41** [comment]
I was reading some jetpref code and I can imagine that after a restart the preferences are no longer found because they are searched for in the wrong place, or that the paths are generated incorrectly before saving. 

Either one of those Files is wrong when loading. [Source](https://github.com/patrickgold/jetpref/blob/5a1590fae52f1405c636dbfe9d91662c2efffdeb/datastore-model/src/main/kotlin/dev/patrickgold/jetpref/datastore/model/PreferenceModel.kt#L222-L225)

```kotlin
        private val datastoreDir: File = context.jetprefDatastoreDir
        private val datastoreFile = datastoreDir.jetprefDatastoreFile(name)
        private val tempDir: File = context.jetprefTempDir
        private val tempFile = tempDir.jetprefTempFile(name)
```
This method fails to create the dirs. [Source](https://github.com/patrickgold/jetpref/blob/5a1590fae52f1405c636dbfe9d91662c2efffdeb/datastore-model/src/main/kotlin/dev/patrickgold/jetpref/datastore/model/PreferenceModel.kt#L241-L244)
```kotlin
        private fun mkdirs() {
            datastoreDir.mkdirs()
            tempDir.mkdirs()
        }
``` 
Or the rename fails for whatever reason. [Source](https://github.com/patrickgold/jetpref/blob/5a1590fae52f1405c636dbfe9d91662c2efffdeb/datastore-model/src/main/kotlin/dev/patrickgold/jetpref/datastore/model/PreferenceModel.kt#L318)
```kotlin
                tempFile.renameTo(datastoreFile)
``` 

Of course, it could be completely different, but these were the places I could imagine from reading the code. Since I can't reproduce this bug either, I can't really debug it directly and can only guess

**Comment by sogood-ood** [comment]
I agree that this problem is most likely due to the fact that after restarting the application (for security reasons) does not have access to the internal storage...
maybe it is possible to somehow make the settings that the user makes more "default" - i.e. make changes not in a separate file, but in the application itself... after all, the application starts with some design (although I had a couple of times when the keyboard did not start at all and there was only a black rectangle).
I'm running LineageOS

**Comment by searinminecraft** [comment]
Can confirm this. This happens if I force restart phone or sudden power loss (removing battery, etc.) Like what others mentioned, this can be real annoying, and I'm one of them.

**Comment by 386jdhJd882gHe** [comment]
I also encountered this

**Comment by Wolfizen** [comment]
I encounter this bug occasionally too. It only happens when my phone loses power. I have never seen it happen with a clean restart.

FlorisBoard Version: 0.4.6 (104)
OS Type: LineageOS
OS Version: 21-20241129-NIGHTLY-aura
OS Build Number: lineage_aura-userdebug 14 AP2A.240905.003 0ea57933d5

### Mitigation

I found a **workaround** for frequent sufferers of this issue. Use the "Back up data" feature in the Advanced settings section to save a settings file on your storage. Then when the bug happens, use the "Restore data" feature in the same settings menu to load the saved file. It is tedious but much faster than configuring the application manually.

**Comment by patrickgold** [comment]
PR #3000 upgrades to JetPref v0.3, which is a complete rewrite of the state and datastore logic. This also has an effect on this bug, which hopefully has been fixed with the new version.

We now need your feedback, especially from those who were able to somewhat consistently reproduce the bug. Using the latest debug artifact from PR #3000, can you still reproduce the bug?

**Comment by Int-Circuit** [comment]
Hi I just restarted my phone and when unlocking it with my password, florisboard beta uses the default theme and default layout (floris night instead of floris pure night and english instead of french layout). I get the message "unable to unzip preferances, fallback to default settings"

Version: 0.5.0-beta03 (111)

**Comment by patrickgold** [comment]
Thanks for the report!

This means the preference load seems to be triggered too early, possibly before the context is valid. If you force close FlorisBoard and then open FlorisBoard again, are the preferences back?

**Comment by patrickgold** [comment]
Also, what did the toast say exactly? Because we don't have that string in our resources...

**Comment by Int-Circuit** [comment]
Here is a photo of the toast:

![Image](https://github.com/user-attachments/assets/e1b4269c-7c8f-40c7-9b5d-21e1c3c17158)

As this is one the lock screen i cannot force quit the app

**Comment by bossmann47** [comment]
Can confirm, the issue is still not fixed.

**Comment by lm41** [comment]
@Int-Circuit this is normal behavior as the user data is not yet decrypted. Are the prefs loaded normal _after_ unlocking the phone the first time?

**Comment by Int-Circuit** [comment]
Yea,  sorry i thought that was the issue. 

Le 4 août 2025 18:32:08 GMT+02:00, "Lars Mühlbauer" ***@***.***> a écrit :

**Comment by patrickgold** [comment]
> Can confirm, the issue is still not fixed.

So for you, the preferences are not loaded AFTER you unlocked the phone for the first time?

The issue with the theme error displaying is another issue, this discussion here focuses on the fact that after decryption of user storage the prefs are lost.

**Comment by patrickgold** [comment]
The stable 0.5.0 is now out for a few weeks, does this issue still occur on your devices? If not I will consider this issue to be fixed.

**Comment by atikattar1104** [comment]
For Me, The Issue Is Fixed. There Is No Form Of Data Loss Happening For Now. Not Even Preferences, Not Clipboard, Everything Works Well. 

For Anyone Else Who's Still Facing This Issue, Please Let Us Know Here.

**Comment by patrickgold** [comment]
I will mark this issue as completed in 0.5 stable release.

**Comment by ssssamstrup** [comment]
This seem to be fixed for me too! 🎊
