### ISSUE TITLE
No suggestions/emoji suggestions displaying

### ISSUE THREAD

**Issue by tacheometry** [florisboard/florisboard#2460]
### Short description

If enabling the **Display suggestions** option and testing out the keyboard, no suggestions show up, including no emojis, and only show the word you're typing with different number suffixes appended. Emoji suggestions don't display either.

<img src="https://github.com/florisboard/florisboard/assets/39647014/b8bce830-36e8-4ba8-9be9-da70c51d553f" width="300">
<img src="https://github.com/florisboard/florisboard/assets/39647014/41740009-4b1e-493b-8120-9e31b5e1e30f" width="300">

My backup file:
[backup_dev.patrickgold.florisboard.beta_94_1714046783601.zip](https://github.com/florisboard/florisboard/files/15109600/backup_dev.patrickgold.florisboard.beta_94_1714046783601.zip)

If there are any more details necessary I can provide them.

Possibly related to #2266 

### Steps to reproduce

1. Enable Display suggestions
2. Type something
3. Suggestions don't work properly

### FlorisBoard Version

0.4.0-beta02

### Install Source

F-Droid

### Device

Motorola G84

### Android

14, Rooted

**Comment by lm41** [comment]
When you import the backup, the first language selected is Romanian, which is not included in https://github.com/florisboard/florisboard/commit/397ef1a150f5e9a62573b313c50ecdca33ac6bda. The language switching doesn't seem to work for the EmojiSuggestions at the moment. (I don't know why). When I switch to English and force stop the keyboard, they start to work.

**Comment by tacheometry** [comment]
Yup 👍 This is it, if the keyboard _starts_ with English, emoji suggestions work. Oddly enough, if I type random characters, I still get the same effect as screenshot 1. But at least emoji suggestions work now

**Comment by patrickgold** [comment]
> Yup 👍 This is it, if the keyboard _starts_ with English, emoji suggestions work. Oddly enough, if I type random characters, I still get the same effect as screenshot 1. But at least emoji suggestions work now

I would expand that to "If the keyboard starts with a supported emoji language the emoji suggestions work", but that explains why this bug made it through testing, good observation!

**Comment by patrickgold** [comment]
I'll work on fixing this bug

**Comment by patrickgold** [comment]
Above linked PR should fix the issue, it would be great if some of you could test it out using the debug artifacts.

**Comment by tacheometry** [comment]
@patrickgold Using the file here? https://github.com/florisboard/florisboard/actions/runs/8862090019

**Comment by patrickgold** [comment]
yes

**Comment by tacheometry** [comment]
I tried it out and it's working. Started it up in Romanian, got no emoji suggestions, then switched to English, and they show up 👍

**Comment by Kreuger** [comment]
This doesnt work for me, with that debug build. I had English (Canada) set by default. I tried switching to US and it still doesnt work. Oddly, it works here on Github but I suspect that they have it built in.

**Comment by polyzen** [comment]
Not getting emoji suggestions here either, with the system language set to "English (United States)".

**Comment by lm41** [comment]
> Not getting emoji suggestions here either, with the system language set to "English (United States)".
> 
> Edit: 0.4.0 installed from GitHub on a Pixel 8 running GrapheneOS (Android 14)

Have you turned on “Show suggestions” in the “Typing” settings?

**Comment by polyzen** [comment]
"Display suggestions" is enabled.

**Comment by lm41** [comment]
![Screenshot_20240918-235347.png](https://github.com/user-attachments/assets/40fe4b10-e584-46e7-ae01-d6bec49e0cbe)


🤷‍♂️

**Comment by polyzen** [comment]
I had to enable the smartbar! Thank you.
