### ISSUE TITLE
Navigation Bar color issue.

### ISSUE THREAD

**Issue by Ansarmughal99** [florisboard/florisboard#2746]
@patrickgold @itsmartashub I can tell u I was having the Navigation bar color issue with Heliboard see pic 1 but after the recent update an option is added in appearance as color navigation bar, see pic 2 after this option there is no issue with color in navigation bar see pic 3 . Might this is not a system issue. 
Pic 1:- ![IMG_20250117_145540.jpg](https://github.com/user-attachments/assets/51e647f4-e661-4775-a927-1b8c77a43dea)

Pic 2 :- ![IMG_20250117_145458.jpg](https://github.com/user-attachments/assets/6d6b274b-774b-48e6-96fa-2f65f0f9a555)

Pic 3:- After Navigation bar color is set On ![IMG_20250117_145532.jpg](https://github.com/user-attachments/assets/7339c264-80e7-4a85-9d05-07a97396ebf6)

_Originally posted by @Ansarmughal99 in https://github.com/florisboard/florisboard/issues/2461#issuecomment-2597807186_

**Comment by Ansarmughal99** [comment]
@patrickgold 
@lm41

**Comment by Ansarmughal99** [comment]
@patrickgold 
@lm41 
This issue negatively impacts the user experience when using the keyboard.
I use the rise keyboard feature to give a dull feel as the bottom side of the keyboard is in  other color while uper in other color.

**Comment by Ansarmughal99** [comment]
![IMG_20250214_201101.jpg](https://github.com/user-attachments/assets/6c0738af-eb4e-48d0-b799-15d63e645c9a)

**Comment by klaurence** [comment]
This might have been fixed for the next release by #2757. @lm41, can you confirm?

**Comment by lm41** [comment]
No. This PR specifically fixes the colors and contentPadding of the BottomSheet activated when editing the smartbar actions.

**Comment by lm41** [comment]
@Ansarmughal99 what is 'the recent update' of heliboard. When posting something like this please be more specific in the future. This way it is easier for us to find the right change.

**Comment by itsmartashub** [comment]
I finally managed to reproduce this issue almost every time.

TLDR: **Material You themes miscalculate colors on wallpaper change** causing system nav and keyboard background inconsistencies?

When using material you themes (floristyle), changing the wallpaper often leaves the **system nav unstyled/mistyled** and also causes the **theme to miscalculate** at first. Some elements, like the keyboard bg, retain colors from the previous wallpaper, while others update correctly. (Think I've mentioned this back then in #2461)

The board bg simply fix themselves when opening the three-dots menu, while the system nav resets after, for example, switching to another keyboard (e.g. Heliboard) and then back to Florisboard. 
Ez temp "fix", but since the @Ansarmughal99 mentioned somewhere his wallpaper changes every 30min I can understand that frustration and his persistence in repeatedly pointing this out 😅

I couldn’t reproduce this in latest Heliboard or with other themes like default Florisboard and Catppuccin, suggesting it’s either a Material You calc related issue or something off in floristyle, which I'll check these days.

PS. for testing with floristyle is recommended to **not use** the **OLED** themes, as its background is a static black color, not material-sourced.

<details>
  <summary><b>VIDEO: Material You theme - recalculating issue</b></summary>
  
https://github.com/user-attachments/assets/5fecd4bb-b882-4a55-a9e3-169f266a420e

  </video>
</details>

**Comment by lm41** [comment]
Hey @itsmartashub and @Ansarmughal99, can you please test if this pr (#2778) fixes the problem. I personally cannot reproduce this issue as I do not have a changing wallpaper.

**Comment by Ansarmughal99** [comment]
@lm41 Working fine from last 6 hours with multiple wallpaper changes .
Thanks for this fix.
Plz Release in stable

**Comment by Ansarmughal99** [comment]
@lm41 Working fine from last 6 hours with multiple wallpaper changes .
Thanks for this fix.
Plz Release in stable

**Comment by lm41** [comment]
@Ansarmughal99 I've dropped some changes to the PR. Can you please test if the changes still work

**Comment by Ansarmughal99** [comment]
@lm41 Facing again Same issue but this time it does  not happen  frequently  as it was before after every wallpaper change, mostly Material ui theme with night or evening theme . I was not facing any issue with floristyle sunshine theme 
Also it gets the same issue   after the phone screen is off and there is a wallpaper change  that shows the same bug.
I will use the debug version and Get back after some time.

**Comment by Ansarmughal99** [comment]
@lm41 
After using it for 2 days i have noticed there is almost 80% less navigation bar bug during light mode with Floristyle Sunshine theme but during dark mode on phone and using dark theme or evening theme  or night theme there are  still issues  but not as it was earlier. Also I have noticed that if wallpaper change and icons on app drawer has not updated the color of wallpaper then the navigation bar shows app drawer icons color while upper keyboard theme shows home screen wallpaper color. This issue is only  encountered 3-4 times  a day  with a light  theme but maximum times on the night theme.

Also I think the update might not be applied in time if the system processes the wallpaper change before FlorisBoard updates the UI.

**Comment by lm41** [comment]
So generally it is better now?

**Comment by lm41** [comment]
> Also I have noticed that if wallpaper change and icons on app drawer has not updated the color of wallpaper then the navigation bar shows app drawer icons color while upper keyboard theme shows home screen wallpaper color.

Long sentence. I don't understand what you mean. Can you provide screenshots or something similar?

**Comment by Ansarmughal99** [comment]
> So generally it is better now?
70-80% of the issue has been resolved. Hopefully, everything will be clear by the next update.

**Comment by Ansarmughal99** [comment]
> > Also I have noticed that if wallpaper change and icons on app drawer has not updated the color of wallpaper then the navigation bar shows app drawer icons color while upper keyboard theme shows home screen wallpaper color.
> 
> Long sentence. I don't understand what you mean. Can you provide screenshots or something similar?

I will send you a screenshot soon as soon as I face this issue again.

**Comment by Unbaised99** [comment]
Hi I am new on florisboard and today installed v0.4.6 and got issue on keyboard theme as bottom of keyboard is having issue of color and it stays with previous color of theme. And changing wallpaper. I think this issue is not fixed and should be reopened.
When using material you themes (floristyle), changing the wallpaper often leaves the system nav unstyled/mistyled and also causes the theme to miscalculate at first. Some elements, like the keyboard bg, retain colors from the previous wallpaper, while others update correctly

![Image](https://github.com/user-attachments/assets/27a5b86e-94c6-4375-808c-1d2b89f80999)
![Image](https://github.com/user-attachments/assets/6873c887-fc68-4115-98a0-c4be604b7b4c)
![Image](https://github.com/user-attachments/assets/203db571-188f-4ccd-a1d1-a7646472baea)

**Comment by patrickgold** [comment]
> Hi I am new on florisboard and today installed v0.4.6 and got issue on keyboard theme as bottom of keyboard

Hmmm that is weird, what is your Android version and which device do you have?

**Comment by Unbaised99** [comment]
> > Hi I am new on florisboard and today installed v0.4.6 and got issue on keyboard theme as bottom of keyboard
> 
> Hmmm that is weird, what is your Android version and which device do you have?

I am using Android 13 with One plus nord CE 4 
Same issue on Samsung a54

**Comment by Ansarmughal99** [comment]
> > Hi I am new on florisboard and today installed v0.4.6 and got issue on keyboard theme as bottom of keyboard
> 
> Hmmm that is weird, what is your Android version and which device do you have?

![IMG_20250313_000144.jpg](https://github.com/user-attachments/assets/bc5f7ffd-d86b-488e-85f0-cafe66d2150e)

![IMG_20250313_000123.jpg](https://github.com/user-attachments/assets/6ab45c2a-8fa0-4701-8e9e-8e6d23d1fccd)

**Comment by lm41** [comment]
Is the backround changing when the keyboard is open?

**Comment by Ansarmughal99** [comment]
> Is the backround changing when the keyboard is open?

It doesn't matter whether the keyboard is open or closed whenever the wallpaper is changed and phone screen is locked and  material you are applying to phones then this bug happens .

**Comment by Unbaised99** [comment]
![IMG_20250315_222438.jpg](https://github.com/user-attachments/assets/1db9aeab-d6ab-4edc-a7e7-48caebd20d86)

![IMG_20250315_222527.jpg](https://github.com/user-attachments/assets/a5e7d1b2-e44f-44b7-bc3a-a171b454d9ab)

**Comment by lm41** [comment]
So everybody facing this issue isn't using stock android? It could be that other OEMs patch out the intent action we are using to detect the wallpaper change (`Intent.ACTION_WALLPAPER_CHANGED`) as it is deprecated since API level 16. If that's the case we won't be able to fix this issue.

**Comment by itsmartashub** [comment]
> So everybody facing this issue isn't using stock android?

I'm so sorry for being afk on this. Yes, all the devices that I could reproduce this **have a custom ROM**. 
But I remember that I couldn't trigger it anymore with your mentioned PR #2778 back then. I hope @Ansarmughal99 can be more helpful on this, or his twin brother @Unbaised99 ;))

**Comment by Ansarmughal99** [comment]
I was waiting for the new PR to be released with the issue resolved, but the latest release still doesn't address it.
Also i dont have any device with stock ROM.

> > So everybody facing this issue isn't using stock android?
> 
> I'm so sorry for being afk on this. Yes, all the devices that I could reproduce this **have a custom ROM**. 
> But I remember that I couldn't trigger it anymore with your mentioned PR #2778 back then. I hope @Ansarmughal99 can be more helpful on this, or his twin brother @Unbaised99 ;)) not sure which account he's more active on

**Comment by patrickgold** [comment]
> I was waiting for the new PR to be released with the issue resolved, but the latest release still doesn't address it.
Also i dont have any device with stock ROM.

So 0.5.0-alpha02 doesn't fix the bug for you?

**Comment by Ansarmughal99** [comment]
> > I was waiting for the new PR to be released with the issue resolved, but the latest release still doesn't address it.
> Also i dont have any device with stock ROM.
> 
> So 0.5.0-alpha02 doesn't fix the bug for you?

This issue occurs when using the Floristyle Material You dynamic theme, which is not supported in version 0.5-alpha2. However, there is no issue with the navigation bar when using the default pre-built theme.

**Comment by patrickgold** [comment]
Yeah but the fix only works from 0.5.0-alpha02 onwards, meaning it makes sense that for the 0.4.6 version the bug is still persistent

**Comment by itsmartashub** [comment]
> which is not supported in version 0.5-alpha2

That makes sense, you don't have the proper environment to test the latest version of Florisboard.

I'm about to release an update, but I just wanted to check with you guys first. Are you already aware of the navbar background issue on light themes?

<details>
<summary>Screenshots</summary>
<img src="https://github.com/user-attachments/assets/74858b0e-b3f0-4267-b0a1-7d2a0dfb9659" width="48%"/>
<img src="https://github.com/user-attachments/assets/44c71537-6034-49ce-aee0-a14f17170a6a" width="48%"/>
</details>

**Comment by Ansarmughal99** [comment]
I am not facing any issue in 0.5 alpha2 but it was 0.5 alpha1
![ScreenShot.jpg](https://github.com/user-attachments/assets/7ce329ec-9b59-4650-bb38-b296313eac8e)



> > which is not supported in version 0.5-alpha2
> 
> That makes sense, you don't have the proper environment to test the latest version of Florisboard.
> 
> I'm about to release an update, but I just wanted to check with you guys first. Are you already aware of the navbar background issue on light themes?
> 
> <details>
> <summary>Screenshots</summary>
> <img src="https://github.com/user-attachments/assets/74858b0e-b3f0-4267-b0a1-7d2a0dfb9659" width="48%"/>
> <img src="https://github.com/user-attachments/assets/44c71537-6034-49ce-aee0-a14f17170a6a" width="48%"/>
> </details>

**Comment by patrickgold** [comment]
> I'm about to release an update, but I just wanted to check with you guys first. Are you already aware of the navbar background issue on light themes?

In your screenshot, do you reference to the extra padding which seems to the exactly the navbar height?

**Comment by Ansarmughal99** [comment]
I've been using it for over 24 hours and haven't faced any issues,  using both day and  night theme . It works well.
Thanks for the fix!

**Comment by lm41** [comment]
Then I assume that the problem has finally been fixed. Phew, it only cost me half my sanity haha.

**Comment by elisenlebkuch** [comment]
I don't know if this is an app or a ROM issue, but for me it is still (or again?) white if I'm using 3 button navigation with any version since v0.5.0-alpha01. When using a dark theme it switches to pitch black. Weirdly it's only like that with the 3 button navbar, when using gesture navigation it adopts the background color correctly.

**Comment by lm41** [comment]
Hey. 
This is caused by enforcing the navigation-bar contrast in the ImeUI,
https://github.com/florisboard/florisboard/blob/ee08c58db204505a85efa0509b826d36944b9614/app/src/main/kotlin/dev/patrickgold/florisboard/lib/compose/SystemUi.kt#L40-L42

I quickly tested it and I think we can remove the enforcement.

**Comment by lm41** [comment]
@elisenlebkuch I have some changes regarding the nav bar in #2987 and testing this APK [1] would be appreciated. 

[1] https://github.com/florisboard/florisboard/actions/runs/16423851143/artifacts/3580055079

**Comment by elisenlebkuch** [comment]
> [@elisenlebkuch](https://github.com/elisenlebkuch) I have some changes regarding the nav bar in [#2987](https://github.com/florisboard/florisboard/pull/2987) and testing this APK [1] would be appreciated.
> 
> [1] https://github.com/florisboard/florisboard/actions/runs/16423851143/artifacts/3580055079

For my personal usecase it works just fine now. I used the debug build from when you opened the PR over the last few day and haven't had any issues with it. Also, from what I saw until now, the build you just linked is good, too.

**Comment by lm41** [comment]
The only things I changed today were that the semi-transparent layer is still displayed when a background image is set, so that the nav bar buttons are visible and that the nav bar button colors are no longer adjusted depending on the theme state but are set directly from the underlying color

**Comment by elisenlebkuch** [comment]
Then it should be fine.
